version: 2.0
jobs:
  build:
    docker:
    - image: cibuilds/drupal:latest
    steps:
      - checkout
      - run:
                name: Where am I?
                command: pwd; ls;cd docroot; drush st;
