version: 2.0
jobs:
  build:
    docker:
      - image: juampynr/drupal8ci:latest
    steps:
      - checkout
      - run:
          name: "Cache Clear"
          command: |
            cd ../docroot
            drush cr
      - run:
          name: Check current version of node
          command: drush st
