version: 2.0
jobs:
  build:
    docker:
    - image: cibuilds/drupal:latest
    steps:
      - checkout
      - run:
          name: "Cache Clear"
          command: |
            cd docroot
      - run:
                name: run composer install to get the vendor directory
                command: composer install

      - run:
          name: Check current version of drush
          command: drush st
